"""add group_type and status

Revision ID: 5dd72d4f2aeb
Revises: a1b2c3d4e5f6
Create Date: 2026-08-02 13:11:16.283139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dd72d4f2aeb'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

group_type_enum = sa.Enum(
    "NORMAL",
    "FRIEND",
    name="grouptype",
)

group_status_enum = sa.Enum(
    "PENDING",
    "ACTIVE",
    "REMOVED",
    name="groupstatus",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    group_type_enum.create(op.get_bind(), checkfirst=True)
    group_status_enum.create(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('idx_friends_owner_id'), table_name='friends')
    op.drop_table('friends')
    op.alter_column('expense_splits', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('group_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('groups', sa.Column('group_type', group_type_enum, nullable=True))
    op.add_column('groups', sa.Column('status', group_status_enum, nullable=True))
    op.execute("""
    UPDATE groups
    SET group_type = 'NORMAL',
    status = 'ACTIVE';
    """)
    op.alter_column("groups", "group_type", nullable=False)
    op.alter_column("groups", "status", nullable=False)
    op.drop_index(op.f('idx_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.alter_column('settlements', 'payer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('settlements', 'receiver_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settlements', 'receiver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('settlements', 'payer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_column('groups', 'status')
    op.drop_column('groups', 'group_type')

    group_status_enum.drop(op.get_bind(), checkfirst=True)
    group_type_enum.drop(op.get_bind(), checkfirst=True)
    op.alter_column('group_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('expense_splits', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('friends',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shadow_group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_friends_owner_id_users')),
    sa.ForeignKeyConstraint(['shadow_group_id'], ['groups.id'], name=op.f('fk_friends_shadow_group_id_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friends')),
    sa.UniqueConstraint('shadow_group_id', name=op.f('uq_friends_shadow_group_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_friends_owner_id'), 'friends', ['owner_id'], unique=False)
    # ### end Alembic commands ###
